config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "/pages/:permalink" => "pages#permalink", as: "permalink"
  root to: "home#index"
  # get 'production_companies/index'
  # get 'production_companies/show'
  # get 'movies/index'
  # get 'movies/show'

  resources :movies, only: %i[index show] do
    collection do
      get "search"
    end
  end
  # movies/search/:id
  resources :production_companies, only: %i[index show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :production_company
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  validates :title, :year, :duration, :description, :average_vote, presence: true
  validates :title, uniqueness: true
  validates :year, :duration, numericality: { only_integers: true }
  validates :average_vote, numericality:

                                         def genres_list
                                           genres.map(&:name).join(", ")
                                         end
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/production_company.rb
class ProductionCompany < ApplicationRecord
  has_many :movies

  validates :name, uniqueness: true

  def self.ordered_by_movies
    self.select("production_companies.*")
        .select("COUNT(production_companies.id) as movie_count")
        .left_joins(:movies)
        .group("production_companies.id")
        .order("movie_count DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages
  def cms_pages
    Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.includes(:production_company).order("average_vote DESC").limit(10)

    @production_companies = ProductionCompany.limit(10)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # @movies = Movie.all # this creates the N+1 problem; +1 refers to movies whereas N refers to
    # production_companies, in short this means we are redundantly callling the database (expensive)
    @movies = Movie.includes(:production_company).all.order("average_vote DESC")
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @movies = Movie.where("title LIKE ?", wildcard_search)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html do
          redirect_to page_url(@page.permalink), notice: "Page was successfully created."
        end
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html do
          redirect_to page_url(@page.permalink), notice: "Page was successfully updated."
        end
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/production_companies_controller.rb
class ProductionCompaniesController < ApplicationController
  def index
    # all production companies
    # @production_companies = ProductionCompany.all

    @production_companies = ProductionCompany.ordered_by_movies
  end

  def show
    # a specific production company
    @production_company = ProductionCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 10 Movies</h2>
    <ol class="ml-5">
      <% @movies.each do |movie| %>
        <li>
          <%= link_to movie.title, movie %> <em>(<%= movie.production_company.name %>)</em>
        </li>
      <% end %>
    </ol>
    <p class="mt-5">
      <strong>
        <%= link_to '🎬 For more Movies', movies_path %>
      </strong>
    </p>
  </div>

  <div class="column">
    <h2 class="title is-2">Top 10 Production Companies</h2>
    <ol class="ml-5">
      <% @production_companies.each do |production_company| %>
        <li>
          <%= link_to production_company.name, production_company %>
        </li>
      <% end %>
    </ol>
    <p class="mt-5">
      <strong>
        <%= link_to '🎥 For more Production Companies', production_companies_path %>
      </strong>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + "-" if content_for?(:html_title)%>Top 100 Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
  <section class="section">
    <div class="container m-0">
      <h1 class="title is-1">Top Movies From IMDB</h1>
      <%= render partial: "movies/form" %>
    </div>
    <%= yield %>
  </section>
  <% if controller_name == 'home' %>
    <p class="pl-5">There is no place like home 🏠</p>
  <% else %>
    <%= render partial: 'layouts/components/footer'%>
  <% end %>
  </body>
</html>

app/views/layouts/components/_footer.html.erb
<hr>
<footer class="pl-5">
  <p><em>Copywrong IMDB 2023 CST</em></p>
  <br>
  <ul class="m5-5">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Top 100 Movies", movies_path%></li>
    <li><%= link_to "Top Production Companies", production_companies_path%></li>

    <% cms_pages.each do |page| %>
      <li><%= link_to page.title, permalink_path(page.permalink) %></li>
    <% end %>
  </ul>
</footer>

app/views/movies/_form.html.erb
<%= form_with(url:search_movies_path, method: :get, local: true) do %>
  <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for Movies") %>
  <%= submit_tag("Search!", class: "button is-primary mt-1") %>
<% end %>

app/views/movies/_movie.html.erb
<h2 class="title is-2">
  <%= movie.title %>
</h2>

<article class="message is-dark">
  <div class="message-header">
    <p>Description</p>
  </div>
  <div class="message-body">
    <%= movie.description %>
  </div>
</article>

<progress class="progress is-info" value=<%=movie.average_vote %> max=10>
  <%= movie.average_vote %>
</progress>

<p>
  <strong>Rating:</strong>
  <%= movie.average_vote %>
</p>

<p>
  <strong>Release Year:</strong>
  <%= movie.year %>
</p>

<p>
  <strong>Duration:</strong>
  <%= movie.duration %>
</p>

<p>
  <strong>Genres:</strong>
  <%= movie.genres_list %>
</p>

<p>
  <strong>Production Company:</strong>
  <%= link_to movie.production_company.name, movie.production_company %>
</p>

app/views/movies/index.html.erb
<h2 class="title is-2">Top 100 Movies</h2>

<ol class="ml-5">
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.title, movie %> was produced by <%= link_to movie.production_company.name, movie.production_company %>
    </li>
  <% end %>
</ol>

<!--
<%= render @movies %>
-->

app/views/movies/search.html.erb
<p class="mb-5">
  Movies found when searching for: <%= params[:keywords] %>
</p>
<u>
  <% @movies.each do |movie| %>
    <li><%= link_to movie.title, movie %></li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<% content_for(:html_title){@movie.title} %>
<%= render @movie %>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class: "textarea" %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink, class: "input" %>
  </div>

  <div>
    <%= form.submit class: "button is-primary mt-5" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", "pages/" + page.permalink %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/production_companies/index.html.erb
<h2 class="title is-2">Production Companies</h2>
<ol>
  <% @production_companies.each do | company| %>
    <li>
      <%= link_to company.name, company %>
      <em>(<%= pluralize company.movie_count, "Top Movie" %>)</em>
    </li>
  <% end %>
</ol>

app/views/production_companies/show.html.erb
<h2 class="title is-2"><%= @production_company.name %></h2>
<p class="mb-5">
  This production company made <%= @production_company.movies.count %> of the top 100 movies.
</p>
<h3 class="title is-3">Movies made by <%= @production_company.name %></h3>
<ul>
  <% @production_company.movies.each do |movie| %>
    <li><%= link_to movie.title, movie %> with a rating of <%= movie.average_vote %></li>
  <% end %>
</ul>